import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { GraphqlProvider } from '@/lib/GraphqlProvider';

const poppins = Poppins({
  weight: ['100', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Luxe Jewels',
  description: 'Generated by create next app',
};
import { AuthProvider } from '@/contexts/AuthProvider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <AuthProvider>
          <GraphqlProvider
            graphqlApiKey={process.env.GRAPHQL_API_KEY as string}
          >
            {children}
          </GraphqlProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
